### ISSUE TITLE
[HELP] NuclearJs reports "TypeError: Cannot read property 'dispatch' of undefined"

### ISSUE THREAD

**Issue by cineq** [optimizely/nuclear-js#215]
Hi I am trying to learn nucearJs from tutorial described on "optimizely.github.io"

I am working on windows. in main.js i try:
```
import reactor from './reactor'
import ProductStore from './stores/ProductStore'
import CartStore from './stores/CartStore'
import actions from './actions'

reactor.registerStores({
  'products': ProductStore,
  'cart': CartStore,
})

reactor.evaluate([]);

actions.fetchProducts([
	{ id: 1, title: "iPad 4 Mini", price: 500.01, inventory: 2, image: "common/assets/ipad-mini.png" },
    { id: 2, title: "H&M T-Shirt White", price: 10.99, inventory: 10, image: "common/assets/t-shirt.png" },
    { id: 3, title: "Charli XCX - Sucker CD", price: 19.99, inventory: 4, image: "common/assets/sucker.png" }
])
```
while my actions.js looks like:
```
import { reactor, toImmutable } from './reactor'
import actionTypes from './actionTypes'

export default {
  fetchProducts(products) {
      reactor.dispatch(actionTypes.RECEIVE_PRODUCTS, { products })
  },

  addToCart(product) {
    reactor.dispatch(actionTypes.ADD_TO_CART, { product })
  },
}
```

Babel compilation finishes succesfully, but during runtime (node main.js) I got error:

```
    _reactor.reactor.dispatch(_actionTypes2.default.RECEIVE_PRODUCTS, { products
: products });
                    ^

TypeError: Cannot read property 'dispatch' of undefined
    at Object.fetchProducts (G:\Git\learn\nuclearJs\build\actions.js:17:21)
    at Object.<anonymous> (G:\Git\learn\nuclearJs\build\main.js:28:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

```

Please help me, I am not very experienced in JavaScript but i wish to study it, and nuclearJS looks very interesting for project I want to develop

**Comment by jordangarcia** [comment]
What does your `reactor.js` file look like?

It needs to be somethink like:

```
import { Reactor } from 'nuclear-js'

const reactor = new Reactor({ debug: true })

export default reactor
```

as seen here: https://github.com/optimizely/nuclear-js/blob/master/examples/shopping-cart/src/reactor.js

**Comment by cineq** [comment]
Yes, my` reactor.js` looks exactly as you described.

`ProductStore `& `CartStore `are also the same as one described in tutorial.

**Comment by raulmatei** [comment]
Hi,

Your imports are messed up, try to import the reactor from reactor.js as:

```js
import reactor from './reactor';
import { toImmutable } from 'nuclear-js';
```

In your `main.js` you're importing it correctly.


Raul.

**Comment by jordangarcia** [comment]
Can this be closed?

**Comment by cineq** [comment]
Yes. I think we can close topic

1 sie 2016 13:09 "Jordan Garcia" <notifications@github.com> napisał(a):
